let mapleader=' '

syntax on
set number
set wildmenu
set showcmd
# set relativenumber

set encoding=utf-8

set nocompatible
filetype on
filetype indent on
filetype plugin on
filetype plugin indent on


set hlsearch
set incsearch
set ignorecase # 忽略搜索大小写
set smartcase # 智能大小写


set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4


set scrolloff=7


colorscheme slate

nnoremap <leader>w :w<CR>

inoremap <C-p> <Up>
inoremap <C-n> <Down>
inoremap <C-b> <Left>
inoremap <C-f> <Right>
inoremap <C-a> <Home>
inoremap <C-e> <End>
inoremap <M-f> <S-Right>
inoremap <M-b> <S-Left>

noremap <C-h> <C-w>h
noremap <C-j> <C-w>j
noremap <C-k> <C-w>k
noremap <C-l> <C-w>l







