# -*- conf -*-

font=LXGW WenKai Mono Medium:size=18

[scrollback]
lines=16384

[main]
include=/usr/share/foot/themes/selenized-dark

[key-bindings]
scrollback-up-half-page=Alt+v
scrollback-down-half-page=Control+v
