# -*- conf -*-

[main]
term=foot-direct
font=Sarasa Mono SC:size=18

include=~/.config/foot/theme

[colors-light]
alpha=0.75
blur=yes

[scrollback]
lines=16384

[key-bindings]
scrollback-up-half-page=Alt+v
scrollback-down-half-page=Control+v
